version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./:/var/www
        depends_on:
            - postgres
    php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
            - ./:/var/www
        depends_on:
            - postgres
        working_dir: /var/www
        tty: true
    postgres:
        image: postgres:9.6-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER=app"
            - "POSTGRES_PASSWORD=secret"
            - "POSTGRES_DB=app"
        ports:
            - "54321:5432"

volumes:
    pgdata:
